<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lambda.cloud</groupId>
        <artifactId>lambda-fusion-parent</artifactId>
        <version>2026.1.1-SNAPSHOT</version>
    </parent>

    <artifactId>lambda-fusion-bom</artifactId>
    <packaging>pom</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-fusion-core</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-fusion-authority</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-fusion-config</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-fusion-dictionary</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-fusion-datasource</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-fusion-permission</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-fusion-oss</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
