<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lamuda.cloud</groupId>
        <artifactId>lamuda-cloud-scaffold-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>lamuda-cloud-scaffold-dependencies</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.lamuda.cloud</groupId>
            <artifactId>lamuda-cloud-scaffold-dict-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lamuda.cloud</groupId>
            <artifactId>lamuda-cloud-scaffold-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lamuda.cloud</groupId>
            <artifactId>lamuda-cloud-scaffold-config</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lamuda.cloud</groupId>
            <artifactId>lamuda-cloud-scaffold-dict</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lamuda.cloud</groupId>
            <artifactId>lamuda-cloud-scaffold-log</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lamuda.cloud</groupId>
            <artifactId>lamuda-cloud-scaffold-message</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lamuda.cloud</groupId>
            <artifactId>lamuda-cloud-scaffold-report</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lamuda.cloud</groupId>
            <artifactId>lamuda-cloud-scaffold-sso</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lamuda.cloud</groupId>
            <artifactId>lamuda-cloud-scaffold-upload</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
