create table la_resources
(
    ID              varchar(64)   not null
        primary key,
    PARENT_ID       varchar(64)   null,
    RES_NAME        varchar(128)  null comment '资源名称',
    RES_PATH        varchar(200)  null comment '访问路径',
    RES_LEVEL       int           null comment '资源级别',
    RES_TYPE        int           null comment '资源类型',
    RES_URL         varchar(510)  null,
    RES_MODE        int default 0 null comment '资源模式 0:后台资源,1:APP资源',
    METHOD          varchar(255)  null comment '对应后台方法函数',
    ICON            varchar(128)  null,
    HIDDEN          int default 0 not null comment '是否隐藏',
    PARENT_KEYS     varchar(1000) null comment '上级节点集',
    IS_DEV          int default 0 not null comment '是否是开发者功能, 0:否,1:是',
    REMARK          varchar(2000) null,
    URL             varchar(255)  null comment '资源路径',
    KEY_NAME        varchar(64)   null comment '国际化KEY',
    KEEP_ALIVE      int default 0 null comment '是否缓存',
    EXPAND          varchar(1024) null comment '扩展字段',
    BUSINESS_EXPAND varchar(1024) null comment '业务扩展字段',
    ORDER_NO        int           not null comment '排序'
)
    comment '资源信息表';

INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('02qO2Uxa', '4y3OpJFy', '管理键值', 'dict_manage', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-4y3OpJFy', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 4);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('0saIaeyh', '9e4sWAdn', '角色分配用户', 'role_set_users', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-9e4sWAdn', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 7);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('1uYLUsrN', 'jw1MUnwu', '资源管理', '/system/menu', 1, 1, null, 0, null, 'lucide:menu', 0, 'jw1MUnwu', 1, null, null, null, 0, null, null, 1);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('2016432791681531905', '4y3OpJFy', '字典删除', '/', 2147483647, 3, '/', 0, null, null, 0, 'jw1MUnwu-4y3OpJFy', 0, null, null, null, 0, null, null, 5);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('2022298020778496002', 'jw1MUnwu', '区域管理', '/system/area', 0, 1, null, 0, null, 'carbon:chart-area', 0, 'jw1MUnwu', 0, null, null, null, 0, null, null, 12);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('2663836d', 'jw1MUnwu', '数据源管理', '/system/datasource', 1, 1, null, 0, null, 'carbon:database-messaging', 0, 'jw1MUnwu', 0, null, null, null, 0, null, null, 12);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('2HflHpka', '9e4sWAdn', '删除角色', 'role_delete', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-9e4sWAdn', 0, null, null, null, 0, null, null, 4);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('2kjRp1vy', 'HbkspYqi', '禁用/启用', 'user_disable', 2147483647, 3, null, 0, null, null, 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false,"cacheIframe":false}', null, 10);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('3XqeIyvx', '9e4sWAdn', '角色设置', 'role_settings', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-9e4sWAdn', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 5);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('4y3O6666', 'jw1MUnwu', '客户端管理', '/system/client', 1, 1, null, 0, '', 'carbon:application-web', 0, 'jw1MUnwu', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false,"cacheIframe":true}', null, 7);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('4y3OpJFy', 'jw1MUnwu', '字典管理', '/system/dict', 1, 1, null, 0, null, 'lucide:book-open', 0, 'jw1MUnwu', 0, null, null, null, 0, null, null, 8);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('5QLeOz8j', '1uYLUsrN', '接口权限设置', 'resource_api_permission', 2147483647, 3, null, 0, null, null, 0, 'jw1MUnwu-1uYLUsrN', 1, null, null, null, 0, '{"strWindowName":"_blank","token":false,"cacheIframe":null}', null, 5);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('7U9hMmAv', 'jw1MUnwu', '租户管理', '/system/tenant', 1, 1, null, 0, '', 'lucide:building', 0, 'jw1MUnwu', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false,"cacheIframe":null}', null, 3);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('7VSFrGbK', 'HbkspYqi', '菜单权限设置', 'user_menu_set', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, null, null, 5);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('8xKLkmLg', 'HbkspYqi', '查看数据权限', 'user_data_view', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, null, null, 6);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('9ATivEP1', 'SBctwOO4', '修改组织', 'org_update', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-SBctwOO4', 0, null, null, null, 0, null, null, 2);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('9e4sWAdn', 'jw1MUnwu', '角色管理', '/system/role', 1, 1, null, 0, null, 'carbon:ibm-quantum-safe-explorer', 0, 'jw1MUnwu', 0, null, null, null, 0, null, null, 4);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('9ThLkx7r', '1uYLUsrN', '新增资源', 'resource_add', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-1uYLUsrN', 1, null, null, null, 0, null, null, 1);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('dKS0HiMX', 'SBctwOO4', '新增组织', 'org_add', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-SBctwOO4', 0, null, null, null, 0, null, null, 1);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('gYWs1nx8', '4y3OpJFy', '删除', 'dict_delete', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-4y3OpJFy', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 3);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('HbkspYqi', 'jw1MUnwu', '用户管理', '/system/user', 1, 1, null, 0, null, 'lucide:users', 0, 'jw1MUnwu', 0, null, null, null, 0, null, null, 5);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('jw1MUnwu', null, '系统管理', '/system', 0, 1, null, 0, null, 'ion:settings-outline', 0, null, 0, null, null, null, 0, null, null, 1);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('l7ixBSOA', 'HbkspYqi', '数据权限设置', 'user_data_set', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, null, null, 7);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('LEpQx7uf', 'HbkspYqi', '更新用户', 'user_edit', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, null, null, 2);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('LoRUXWNx', 'HbkspYqi', '新增用户', 'user_add', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, null, null, 1);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('MI11NxXp', 'HbkspYqi', '用户在线配置', 'user_settings', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 9);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('O4HbLPnb', '1uYLUsrN', '更新资源', 'resource_edit', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-1uYLUsrN', 1, null, null, null, 0, null, null, 2);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('OaiclMMf', 'jw1MUnwu', '系统配置', '/system/config', 1, 1, 'https://hlcxcx.hua001.net/?id=1812000000118401', 0, null, 'carbon:document-configuration', 0, 'jw1MUnwu', 1, null, '', null, 0, null, null, 10);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('ORvXmJpF', 'jw1MUnwu', '系统日志', '/system/logs', 1, 1, null, 0, null, 'carbon:catalog-publish', 1, 'jw1MUnwu', 0, null, null, null, 0, null, null, 9);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('PjHaWJx2', 'HbkspYqi', '查看菜单权限', 'user_menu_view', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, null, null, 4);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('qfyqs8ON', 'SBctwOO4', '创建根组织', 'org_top_add', 2147483647, 3, null, 0, null, null, 0, 'jw1MUnwu-SBctwOO4', 0, null, null, null, 0, null, null, 4);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('RqF8NqkW', 'HbkspYqi', '权限复制', 'user_permission_copy', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, null, null, 8);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('SBctwOO4', 'jw1MUnwu', '组织管理', '/system/organization', 1, 1, null, 0, null, 'carbon:group-presentation', 0, 'jw1MUnwu', 0, null, null, null, 0, null, null, 6);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('SEweDODm', '9e4sWAdn', '新增角色', 'role_add', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-9e4sWAdn', 0, null, null, null, 0, null, null, 2);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('SGA8j7Hw', '4y3OpJFy', '新增', 'dict_add', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-4y3OpJFy', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 1);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('sr0Cjp0o', '1uYLUsrN', '删除资源', 'resource_delete', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-1uYLUsrN', 1, null, null, null, 0, null, null, 3);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('SXY72GTE', '9e4sWAdn', '权限设置', 'role_permission', 2147483647, 3, null, 0, null, null, 0, 'jw1MUnwu-9e4sWAdn', 0, null, null, null, 0, null, null, 1);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('szZb5mA7', 'HbkspYqi', '解锁', 'user_unlock', 2147483647, 3, null, 0, null, null, 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false,"cacheIframe":null}', null, 11);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('TiO5ZiKz', 'SBctwOO4', '组织启用', 'org_enable', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-SBctwOO4', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 6);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('UFW4x4OQ', 'HbkspYqi', '删除用户', 'user_delete', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-HbkspYqi', 0, null, null, null, 0, null, null, 3);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('VxFZl4Zf', '4y3OpJFy', '编辑', 'dict_edit', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-4y3OpJFy', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 2);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('WohiuT0I', '1uYLUsrN', '移动资源', 'resource_move', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-1uYLUsrN', 1, null, null, null, 0, null, null, 4);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('XAhoKjZM', 'SBctwOO4', '数据权限设置', 'org_data_permission', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-SBctwOO4', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 7);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('xUmLnLQy', '9e4sWAdn', '更新角色', 'role_edit', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-9e4sWAdn', 0, null, null, null, 0, null, null, 3);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('y3hanied', 'SBctwOO4', '删除组织', 'org_delete', 2147483647, 3, null, 0, '', null, 0, 'jw1MUnwu-SBctwOO4', 0, null, null, null, 0, null, null, 3);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('Y8VMO5MS', 'SBctwOO4', '组织禁用', 'org_disable', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-SBctwOO4', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 5);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('YZELcKaI', 'jw1MUnwu', '文件管理', '/system/upload', 1, 1, null, 0, null, 'carbon:ibm-cloud-vpc-file-storage', 0, 'jw1MUnwu', 0, null, null, null, 0, null, null, 11);
INSERT INTO lambda_cloud.la_resources (ID, PARENT_ID, RES_NAME, RES_PATH, RES_LEVEL, RES_TYPE, RES_URL, RES_MODE, METHOD, ICON, HIDDEN, PARENT_KEYS, IS_DEV, REMARK, URL, KEY_NAME, KEEP_ALIVE, EXPAND, BUSINESS_EXPAND, ORDER_NO) VALUES ('zipushcB', '9e4sWAdn', '角色禁用启用', 'role_enable_disable', 2147483647, 3, null, 0, '', '', 0, 'jw1MUnwu-9e4sWAdn', 0, null, null, null, 0, '{"strWindowName":"_blank","token":false}"', null, 6);
