INSERT INTO `la_user_roles` (`USERNAME`, `AUTHORITY`, `TENANT_ID`) VALUES ('111', 'ROLE_TENANT', NULL);
INSERT INTO `la_user_roles` (`USERNAME`, `AUTHORITY`, `TENANT_ID`) VALUES ('13303820660', 'ROLE_DEV', NULL);
INSERT INTO `la_user_roles` (`USERNAME`, `AUTHORITY`, `TENANT_ID`) VALUES ('17610125091', 'ROLE_ADMIN', NULL);
INSERT INTO `la_user_roles` (`USERNAME`, `AUTHORITY`, `TENANT_ID`) VALUES ('17610125091', 'ROLE_DEV', NULL);
